workflows:
  ios-workflow:
    name: iOS Workflow

    environment:
      node: latest
      xcode: latest

    scripts:
      - npm install
      - npm run build
      - npx cap sync ios

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App

    artifacts:
      - build/ios/ipa/*.ipa